# Generated by Django 4.1 on 2022-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_prueba2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba2',
            name='subtitulo2',
            field=models.CharField(max_length=50, verbose_name='Ingrese el subtitulo'),
        ),
        migrations.AlterField(
            model_name='prueba2',
            name='titulo2',
            field=models.CharField(max_length=30, verbose_name='Ingrese el titulo'),
        ),
    ]
