# Generated by Django 4.1 on 2022-10-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_remove_prueba_subtitulo_remove_prueba2_subtitulo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstCiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadocivil', models.CharField(blank=True, max_length=50, verbose_name='Estado Civil')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='estadocivil',
            field=models.OneToOneField(blank=True, default=24, on_delete=django.db.models.deletion.CASCADE, to='empleado.estciv'),
            preserve_default=False,
        ),
    ]
