# Generated by Django 4.1 on 2022-10-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_rename_estadocivil_empleado_situacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Situacion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='Situacion',
            field=models.ManyToManyField(to='empleado.estciv'),
        ),
    ]
