# Generated by Django 4.1 on 2022-10-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_remove_empleado_situacion_empleado_situacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Habilidad',
            field=models.ManyToManyField(to='empleado.habilidades'),
        ),
    ]
