# Generated by Django 4.1 on 2022-10-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0009_empleado_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Mail'),
        ),
    ]
