# Generated by Django 4.1 on 2022-10-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_and_more'),
        ('empleado', '0010_empleado_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('nombre', 'departamento', 'email')},
        ),
    ]
