# Generated by Django 4.1 on 2023-10-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_alter_empleado_unique_together_empleado_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='foto',
        ),
    ]
