# Generated by Django 4.2.6 on 2023-10-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0012_remove_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/', verbose_name='Foto de perfil'),
        ),
    ]
